#!/usr/bin/env python3
"""Regenerate the configuration reference tables in README.md.

The tables are derived from `inferwatch.config.SPEC` and the argparse parser, so
documentation cannot drift from the code.  Run after changing either:

    .venv/bin/python scripts/gen-config-docs.py          # rewrite README.md
    .venv/bin/python scripts/gen-config-docs.py --check   # fail if stale (CI)

The generated block lives between the BEGIN/END markers in README.md; edit the
prose around it freely.
"""

from __future__ import annotations

import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from inferwatch.config import GROUPS, SOURCE_KINDS, SPEC  # noqa: E402
from inferwatch.main import FLAG_TO_KEY  # noqa: E402

BEGIN = "<!-- BEGIN generated: configuration reference -->"
END = "<!-- END generated: configuration reference -->"


def fmt_default(setting) -> str:
    if isinstance(setting.default, bool):
        return "`true`" if setting.default else "`false`"
    return f"`{setting.default}`"


def fmt_range(setting) -> str:
    if setting.choices:
        return ", ".join(f"`{c}`" for c in setting.choices)
    if setting.minimum is not None and setting.maximum is not None:
        return f"{setting.minimum:g}–{setting.maximum:g}"
    if setting.minimum is not None:
        return f"≥ {setting.minimum:g}"
    if setting.type == "duration":
        return "`30s` `15m` `6h` `7d`"
    if setting.type == "backfill":
        return "`7d`, or `-2 days` / `@epoch`"
    return "—"


def settings_tables() -> list[str]:
    out = []
    for group in GROUPS:
        items = [s for s in SPEC if s.group == group]
        if not items:
            continue
        out.append(f"#### {group}\n")
        out.append("| Setting | Default | Accepts | Environment variable | Notes |")
        out.append("|---|---|---|---|---|")
        for s in items:
            notes = []
            if s.restart:
                notes.append("**restart required**")
            if s.help:
                notes.append(s.help.replace("\n", " "))
            out.append(f"| `{s.key}` | {fmt_default(s)} | {fmt_range(s)} "
                       f"| `{s.env}` | {' — '.join(notes) or '—'} |")
        out.append("")
    return out


def source_tables() -> list[str]:
    out = ["#### Source fields\n",
           "Set these with `--set key=value` on `sources add`, or in the "
           "Settings tab.\n"]
    for kind, spec in SOURCE_KINDS.items():
        out.append(f"**{spec['label']}** (`--kind {kind}`)\n")
        out.append("| Field | Default | Required when | Notes |")
        out.append("|---|---|---|---|")
        for f in spec["fields"]:
            default = f.get("default")
            default = f"`{default}`" if default not in (None, "") else "—"
            when = f.get("when")
            when = (", ".join(f"`{k}={v}`" for k, v in when.items()) if when else "—")
            choices = (" One of " + ", ".join(f"`{c}`" for c in f["choices"]) + "."
                       if f.get("choices") else "")
            out.append(f"| `{f['key']}` | {default} | {when} "
                       f"| {(f.get('help') or '').replace(chr(10), ' ')}{choices} |")
        out.append("")
    return out


def flag_table() -> list[str]:
    # Rebuild the parser the way main.py does, without running a command, so the
    # table lists exactly the flags the program accepts.
    import inferwatch.main as m
    parser = argparse.ArgumentParser(prog="inferwatch")
    m._common(parser)

    out = ["#### Command-line flags\n",
           "| Flag | Purpose | Pins the setting |", "|---|---|---|"]
    for action in parser._actions:
        if not action.option_strings or action.dest == "help":
            continue
        flag = ", ".join(f"`{o}`" for o in action.option_strings)
        key = FLAG_TO_KEY.get(action.dest)
        out.append(f"| {flag} | {(action.help or '—')} "
                   f"| {f'`{key}`' if key else '—'} |")
    out.append("")
    out.append("Flags that pin a setting outrank both the environment and the "
               "Settings tab; the tab shows those keys read-only with their origin.")
    out.append("")
    return out


def build() -> str:
    lines = [BEGIN, "",
             "_Generated by `scripts/gen-config-docs.py` — do not edit by hand._",
             ""]
    lines += settings_tables()
    lines += source_tables()
    lines += flag_table()
    lines.append(END)
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if README.md is out of date")
    args = ap.parse_args()

    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    path = os.path.join(root, "README.md")
    with open(path, encoding="utf-8") as fh:
        readme = fh.read()

    block = build()
    if BEGIN not in readme or END not in readme:
        print(f"markers not found in {path}; add:\n{BEGIN}\n{END}", file=sys.stderr)
        return 2
    head, rest = readme.split(BEGIN, 1)
    _old, tail = rest.split(END, 1)
    updated = head + block + tail

    if args.check:
        if updated != readme:
            print("README.md configuration reference is out of date; run "
                  "scripts/gen-config-docs.py", file=sys.stderr)
            return 1
        print("README.md configuration reference is up to date")
        return 0

    if updated != readme:
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(updated)
        print(f"updated {path}")
    else:
        print("no change")
    return 0


if __name__ == "__main__":
    sys.exit(main())
